apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx${BUILD_NUMBER}
spec:
  selector:
    matchLabels:
      app: nginx${BUILD_NUMBER}
  replicas: 1 
  template: 
    metadata:
      labels:
        app: nginx${BUILD_NUMBER}
    spec:
      containers:
      - name: nginx${BUILD_NUMBER}
        image: shanmukhashan022/new_jenkins1:${BUILD_NUMBER}
        ports:
        - containerPort: 80${BUILD_NUMBER}
        imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: nginx${BUILD_NUMBER}
spec:
  type: LoadBalancer
  selector:
    app: nginx${BUILD_NUMBER}
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80${BUILD_NUMBER}